spring:
  application:
    name: FlavorSyncBackend

  datasource:
    url: jdbc:postgresql://localhost:5432/FlavorSyncDB
    username: postgres
    password: admin123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  profiles:
    active: dev
